server:
  port: 8081

razorpay:
  key: KEY
  secret: SECRET_KEY

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentsdb?useSSL=false&serverTimezone=UTC
    username: root
    password: PASSWOD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
